<?php
if(!defined('DIYA')) define('DIYA', 'Дія');
if(!defined('ID')) define('ID', 'ID');
if(!defined('NAME')) define('NAME', 'Назва');
if(!defined('NAMEFULL')) define('NAMEFULL', 'Назва (повна)');
if(!defined('TYPE')) define('TYPE', 'Умовне позначення');
if(!defined('NUMBER')) define('NUMBER', 'Індивідуальний номер');
if(!defined('PODRAZDELENIE')) define('PODRAZDELENIE', 'Підрозділ');
if(!defined('DIAPAZON')) define('DIAPAZON', 'Діапазон вимірювання');
if(!defined('EDIZM')) define('EDIZM', 'Одиниця вимірювання');
if(!defined('POHIBKA')) define('POHIBKA', 'Клас точності (похибка)');
if(!defined('MINSHKALY')) define('MINSHKALY', 'Нижня межа вимірювання');
if(!defined('MAXSHKALY')) define('MAXSHKALY', 'Верхня межа вимірювання');
if(!defined('GROUP')) define('GROUP', 'Група ЗВТ');
if(!defined('KABINET')) define('KABINET', 'Кабінет');
if(!defined('WORK')) define('WORK', 'Вид робіт');
if(!defined('PERIODMETROLOGY')) define('PERIODMETROLOGY', 'Період пров. робіт, міс.');
if(!defined('DATELASTWORK')) define('DATELASTWORK', 'Дата остан. викон. робіт');
if(!defined('LABORATORY')) define('LABORATORY', 'Лабораторія, що виконує роботи');
if(!defined('LABORATORYMESTO')) define('LABORATORYMESTO', 'Місце виконання робіт');
if(!defined('LABORATORYOBLADNANNYA')) define('LABORATORYOBLADNANNYA', 'Обладнання лабораторії');
if(!defined('BRIGADE')) define('BRIGADE', 'Бригада');
if(!defined('PERIODPPR')) define('PERIODPPR', 'Період пров. ППР, міс.');
if(!defined('PERIODTO')) define('PERIODTO', 'Період пров. TO, міс.');
if(!defined('PERIODVERIFICATION')) define('PERIODVERIFICATION', 'Період пров. вериф., міс.');
if(!defined('CENAKALIBROVKI')) define('CENAKALIBROVKI', 'Вартість калібр., грн.');
if(!defined('KODKALIBROVKI')) define('KODKALIBROVKI', 'Код калібрування');
if(!defined('CENAPOVERKI')) define('CENAPOVERKI', 'Вартість повірки, грн.');
if(!defined('KODPOVERKI')) define('KODPOVERKI', 'Код повірки');
if(!defined('STATUS')) define('STATUS', 'Статус');
if(!defined('DATEPLANWORK')) define('DATEPLANWORK', 'Строк виконання');
if(!defined('DATEFACTWORK')) define('DATEFACTWORK', 'Дата виконання');
if(!defined('DATEBIRKA')) define('DATEBIRKA', 'Дата на бирці');
if(!defined('DATEPROTOCOL')) define('DATEPROTOCOL', 'Дата протоколу');
if(!defined('ADRESS')) define('ADRESS', 'Адреса');
if(!defined('DIRPOSADA')) define('DIRPOSADA', 'Посада керівника');
if(!defined('DIRNAME')) define('DIRNAME', 'ПІБ керівника');
if(!defined('EDRPOU')) define('EDRPOU', 'ЄДРПОУ');
if(!defined('TEL')) define('TEL', 'Телефон');
if(!defined('IBAN')) define('IBAN', 'IBAN');
if(!defined('PIB')) define('PIB', 'П.І.Б.');
if(!defined('ROLE')) define('ROLE', 'Статус');

